-- ============================================================================
-- Límite de intentos (rate limiting) para las funciones que cualquiera puede
-- llamar sin iniciar sesión. Sin esto:
--   - get_order_by_customer / cancel_order_by_customer podían usarse para
--     recorrer números de pedido (correlativos) o teléfonos hasta encontrar
--     una coincidencia y leer/anular pedidos de otros clientes (enumeración).
--   - place_order y el formulario de contacto podían llamarse en bucle para
--     generar pedidos o mensajes falsos sin límite (spam / agotar stock).
--
-- No dependemos de la IP del visitante (Supabase no la expone de forma
-- fiable a las funciones de Postgres), así que el límite se aplica por
-- teléfono normalizado y, en las consultas de pedido, también por número de
-- pedido: así no sirve de nada ni probar muchos teléfonos contra un mismo
-- pedido, ni probar muchos pedidos con un mismo teléfono.
--
-- Cómo aplicar este script:
--   1. Ejecuta antes supabase/harden_place_order.sql, supabase/cancel_order.sql
--      y supabase/get_order_by_customer.sql si no lo has hecho ya (este script
--      sustituye las funciones que crean, añadiéndoles el límite de intentos).
--   2. Abre tu proyecto en https://supabase.com/dashboard
--   3. Ve a "SQL Editor" > "New query"
--   4. Pega el contenido de este archivo y ejecútalo (Run)
-- ============================================================================

create table if not exists public.rate_limit_attempts (
  id bigint generated by default as identity primary key,
  bucket_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists rate_limit_attempts_bucket_created_idx
  on public.rate_limit_attempts (bucket_key, created_at desc);

-- Sin RLS abierta a nadie: solo las funciones SECURITY DEFINER de más abajo
-- (que se ejecutan como el dueño de la tabla) pueden leerla o escribirla.
alter table public.rate_limit_attempts enable row level security;

-- Cuenta los intentos recientes de "bucket_key" y falla si supera el límite;
-- si no, registra este intento. p_window_minutes acota además la limpieza,
-- para que la tabla no crezca sin límite.
create or replace function public._rate_limit_check(
  p_bucket_key text,
  p_max_attempts int,
  p_window_minutes int
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  delete from public.rate_limit_attempts
    where created_at < now() - (p_window_minutes || ' minutes')::interval;

  select count(*) into v_count
    from public.rate_limit_attempts
    where bucket_key = p_bucket_key
      and created_at > now() - (p_window_minutes || ' minutes')::interval;

  if v_count >= p_max_attempts then
    raise exception 'Demasiados intentos. Espera unos minutos y vuelve a intentarlo.';
  end if;

  insert into public.rate_limit_attempts (bucket_key) values (p_bucket_key);
end;
$$;

-- --- place_order: máximo 6 pedidos por teléfono cada 60 minutos ------------
create or replace function public.place_order(
  p_customer_name text,
  p_phone text,
  p_email text,
  p_pickup_time text,
  p_items jsonb,
  p_notes text,
  p_origin text
) returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_item jsonb;
  v_product public.products;
  v_quantity int;
  v_total numeric := 0;
  v_resolved_items jsonb := '[]'::jsonb;
begin
  perform public._rate_limit_check(
    'place_order:phone:' || regexp_replace(p_phone, '\s', '', 'g'), 6, 60
  );

  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido no tiene artículos';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item->>'quantity')::int;
    if v_quantity is null or v_quantity <= 0 then
      raise exception 'Cantidad inválida para un artículo del pedido';
    end if;

    select * into v_product from public.products where id = (v_item->>'productId')::uuid;
    if v_product.id is null then
      raise exception 'Producto no encontrado';
    end if;

    v_total := v_total + (v_product.price * v_quantity);
    v_resolved_items := v_resolved_items || jsonb_build_object(
      'productId', v_product.id,
      'name', v_product.name,
      'price', v_product.price,
      'quantity', v_quantity
    );

    update public.products
      set stock = greatest(0, stock - v_quantity)
      where id = v_product.id;

    insert into public.stock_movements (product_id, product_name, type, quantity)
    values (v_product.id, v_product.name, 'venta', -v_quantity);
  end loop;

  insert into public.orders (customer_name, phone, email, pickup_time, items, total, notes, origin, status)
  values (p_customer_name, p_phone, p_email, p_pickup_time, v_resolved_items, v_total, p_notes, p_origin, 'pendiente')
  returning * into v_order;

  return v_order;
end;
$$;

grant execute on function public.place_order(text, text, text, text, jsonb, text, text) to anon, authenticated;

-- --- get_order_by_customer / cancel_order_by_customer ------------------------
-- Máximo 8 intentos cada 15 minutos por teléfono probado y, por separado, 8
-- intentos cada 15 minutos por número de pedido probado (comparten el mismo
-- contador entre las dos funciones, para que no sirva usar una para
-- "recargar" los intentos de la otra).
create or replace function public.get_order_by_customer(p_order_id bigint, p_phone text)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_phone text := regexp_replace(p_phone, '\s', '', 'g');
begin
  perform public._rate_limit_check('lookup:phone:' || v_phone, 8, 15);
  perform public._rate_limit_check('lookup:order:' || p_order_id::text, 8, 15);

  select * into v_order from public.orders
    where id = p_order_id
    and regexp_replace(phone, '\s', '', 'g') = v_phone;

  -- Mensaje genérico a propósito: no revela si falló el número de pedido o
  -- el teléfono, para no facilitar que alguien vaya probando combinaciones.
  if v_order.id is null then
    raise exception 'No se ha encontrado ningún pedido con ese número y teléfono';
  end if;

  return v_order;
end;
$$;

grant execute on function public.get_order_by_customer(bigint, text) to anon, authenticated;

create or replace function public.cancel_order_by_customer(p_order_id bigint, p_phone text)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_item jsonb;
  v_phone text := regexp_replace(p_phone, '\s', '', 'g');
begin
  perform public._rate_limit_check('lookup:phone:' || v_phone, 8, 15);
  perform public._rate_limit_check('lookup:order:' || p_order_id::text, 8, 15);

  select * into v_order from public.orders
    where id = p_order_id
    and regexp_replace(phone, '\s', '', 'g') = v_phone;

  if v_order.id is null then
    raise exception 'No se ha encontrado ningún pedido con ese número y teléfono';
  end if;

  if v_order.status = 'entregado' then
    raise exception 'Este pedido ya se entregó y no se puede anular';
  end if;

  if v_order.status <> 'cancelado' then
    for v_item in select * from jsonb_array_elements(v_order.items)
    loop
      update public.products
        set stock = stock + (v_item->>'quantity')::int
        where id = (v_item->>'productId')::uuid;

      insert into public.stock_movements (product_id, product_name, type, quantity)
      values (
        (v_item->>'productId')::uuid,
        v_item->>'name',
        'cancelacion',
        (v_item->>'quantity')::int
      );
    end loop;

    update public.orders set status = 'cancelado' where id = p_order_id returning * into v_order;
  end if;

  return v_order;
end;
$$;

grant execute on function public.cancel_order_by_customer(bigint, text) to anon, authenticated;

-- --- Formulario de contacto: máximo 5 mensajes por teléfono cada 60 minutos --
create or replace function public.contact_messages_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public._rate_limit_check(
    'contact:phone:' || regexp_replace(new.phone, '\s', '', 'g'), 5, 60
  );
  return new;
end;
$$;

drop trigger if exists contact_messages_rate_limit_trigger on public.contact_messages;
create trigger contact_messages_rate_limit_trigger
  before insert on public.contact_messages
  for each row execute function public.contact_messages_rate_limit();
