-- ============================================================================
-- Catálogo, pedidos, stock y horarios compartidos (sustituye al localStorage
-- por navegador). Idempotente: se puede volver a ejecutar sin error.
-- ============================================================================

-- --- Datos del negocio (fila única) ----------------------------------------
create table if not exists public.business_info (
  id int primary key default 1,
  name text not null,
  tagline text not null,
  address text not null,
  city text not null,
  phone text not null,
  whatsapp text not null,
  instagram text,
  lat double precision not null,
  lng double precision not null,
  google_maps_url text not null,
  rating numeric not null default 0,
  rating_count int not null default 0,
  constraint business_info_singleton check (id = 1)
);

alter table public.business_info enable row level security;

drop policy if exists "business_info_select_public" on public.business_info;
create policy "business_info_select_public" on public.business_info
  for select to anon, authenticated using (true);

drop policy if exists "business_info_update_gerente" on public.business_info;
create policy "business_info_update_gerente" on public.business_info
  for update to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'));

-- --- Productos ---------------------------------------------------------------
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  description text not null default '',
  price numeric not null,
  stock int not null default 0,
  min_stock int not null default 0,
  active boolean not null default true,
  emoji text not null default '🍽️',
  photo text,
  popular boolean not null default false,
  days text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "products_select_public" on public.products;
create policy "products_select_public" on public.products
  for select to anon, authenticated using (true);

drop policy if exists "products_write_gerente" on public.products;
create policy "products_write_gerente" on public.products
  for all to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'));

-- --- Horarios semanales (clave natural: el día) -------------------------------
create table if not exists public.schedules (
  day text primary key,
  open boolean not null,
  open_time text not null,
  close_time text not null
);

alter table public.schedules enable row level security;

drop policy if exists "schedules_select_public" on public.schedules;
create policy "schedules_select_public" on public.schedules
  for select to anon, authenticated using (true);

drop policy if exists "schedules_write_gerente" on public.schedules;
create policy "schedules_write_gerente" on public.schedules
  for all to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'));

-- --- Franjas horarias de recogida (clave natural: la hora) --------------------
create table if not exists public.time_slots (
  time text primary key,
  max_orders int not null default 5
);

alter table public.time_slots enable row level security;

drop policy if exists "time_slots_select_public" on public.time_slots;
create policy "time_slots_select_public" on public.time_slots
  for select to anon, authenticated using (true);

drop policy if exists "time_slots_write_gerente" on public.time_slots;
create policy "time_slots_write_gerente" on public.time_slots
  for all to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'));

-- --- Pedidos -------------------------------------------------------------------
-- Sin acceso directo para nadie (ni siquiera para leer): toda la escritura pasa
-- por las funciones place_order / set_order_status de más abajo, así un cliente
-- anónimo puede "hacer un pedido" sin poder leer los pedidos de otros clientes.
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  pickup_time text not null,
  items jsonb not null,
  total numeric not null,
  notes text,
  status text not null default 'pendiente' check (status in ('pendiente', 'entregado', 'cancelado')),
  origin text not null check (origin in ('web', 'telefono')),
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

drop policy if exists "orders_gerente_only" on public.orders;
create policy "orders_gerente_only" on public.orders
  for all to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'));

-- --- Movimientos de stock --------------------------------------------------------
create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  date timestamptz not null default now(),
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  type text not null check (type in ('entrada', 'venta', 'ajuste', 'cancelacion')),
  quantity int not null
);

alter table public.stock_movements enable row level security;

drop policy if exists "stock_movements_gerente_only" on public.stock_movements;
create policy "stock_movements_gerente_only" on public.stock_movements
  for all to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente'));

-- --- Vista pública de ocupación de franjas (sin datos personales) ----------------
create or replace view public.slot_occupancy as
  select pickup_time as time, count(*) as used
  from public.orders
  where status <> 'cancelado'
  group by pickup_time;

grant select on public.slot_occupancy to anon, authenticated;

-- --- Hacer un pedido (llamable por cualquiera, incluso sin sesión) ---------------
-- Inserta el pedido, descuenta stock de cada línea y registra el movimiento de
-- venta correspondiente, todo en una única transacción.
create or replace function public.place_order(
  p_customer_name text,
  p_phone text,
  p_pickup_time text,
  p_items jsonb,
  p_total numeric,
  p_notes text,
  p_origin text
) returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_item jsonb;
begin
  insert into public.orders (customer_name, phone, pickup_time, items, total, notes, origin, status)
  values (p_customer_name, p_phone, p_pickup_time, p_items, p_total, p_notes, p_origin, 'pendiente')
  returning * into v_order;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    update public.products
      set stock = greatest(0, stock - (v_item->>'quantity')::int)
      where id = (v_item->>'productId')::uuid;

    insert into public.stock_movements (product_id, product_name, type, quantity)
    values (
      (v_item->>'productId')::uuid,
      v_item->>'name',
      'venta',
      -((v_item->>'quantity')::int)
    );
  end loop;

  return v_order;
end;
$$;

grant execute on function public.place_order(text, text, text, jsonb, numeric, text, text) to anon, authenticated;

-- --- Cambiar el estado de un pedido (solo gerentes) ------------------------------
-- Si se cancela un pedido que no estaba ya cancelado, repone el stock y registra
-- los movimientos de cancelación correspondientes.
create or replace function public.set_order_status(p_order_id bigint, p_status text)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_item jsonb;
begin
  if not exists (select 1 from public.profiles where id = auth.uid() and role = 'gerente') then
    raise exception 'Solo los gerentes pueden cambiar el estado de un pedido';
  end if;

  select * into v_order from public.orders where id = p_order_id;
  if v_order.id is null then
    raise exception 'Pedido % no encontrado', p_order_id;
  end if;

  if p_status = 'cancelado' and v_order.status <> 'cancelado' then
    for v_item in select * from jsonb_array_elements(v_order.items)
    loop
      update public.products
        set stock = stock + (v_item->>'quantity')::int
        where id = (v_item->>'productId')::uuid;

      insert into public.stock_movements (product_id, product_name, type, quantity)
      values (
        (v_item->>'productId')::uuid,
        v_item->>'name',
        'cancelacion',
        (v_item->>'quantity')::int
      );
    end loop;
  end if;

  update public.orders set status = p_status where id = p_order_id returning * into v_order;
  return v_order;
end;
$$;

grant execute on function public.set_order_status(bigint, text) to authenticated;
